package jogo;

import aLojinhaClasses.Jogador;
import aLojinhaClasses.Personagem;
import java.util.Random;
import javax.swing.JOptionPane;


public class CriarPersonagem extends javax.swing.JFrame {
    static Jogador jogador;
    private String nome, classe = "";
    private String forcaDados, vidaDados, armaduraDados, poderDados;
    
    int qntDados = 9; // Dados para rodar atributos qntDados+4

    Random gerador = new Random();
    
    int vidaTemp, vidaBonus = 0;
    int armaduraTemp, armaduraBonus = 0;
    int poderTemp, poderBonus = 0;
    int forcaTemp, forcaBonus = 0;
    
    Personagem perso = new Personagem();

    public CriarPersonagem() {
        initComponents();
        geraValoresVida();
        geraValoresArmadura();
        geraValoresForca();
        geraValoresPoder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        lblMago = new javax.swing.JLabel();
        lblGuerreiro = new javax.swing.JLabel();
        lblBotaoProximo = new javax.swing.JLabel();
        lblArqueiro = new javax.swing.JLabel();
        lblArmadura = new javax.swing.JLabel();
        lblPoder = new javax.swing.JLabel();
        lblForca = new javax.swing.JLabel();
        lblDados = new javax.swing.JLabel();
        lblVida = new javax.swing.JLabel();
        imageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/icone.png")).getImage());
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(null);

        txtNome.setOpaque(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome);
        txtNome.setBounds(150, 110, 330, 35);

        lblMago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magoCriarPersonagem.png"))); // NOI18N
        lblMago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMagoMouseClicked(evt);
            }
        });
        jPanel1.add(lblMago);
        lblMago.setBounds(860, 340, 130, 160);

        lblGuerreiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guerreiroCriarPersonagem.png"))); // NOI18N
        lblGuerreiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGuerreiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGuerreiroMouseClicked(evt);
            }
        });
        jPanel1.add(lblGuerreiro);
        lblGuerreiro.setBounds(870, 510, 130, 160);

        lblBotaoProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botaoProximo.png"))); // NOI18N
        lblBotaoProximo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotaoProximoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBotaoProximoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBotaoProximoMouseReleased(evt);
            }
        });
        jPanel1.add(lblBotaoProximo);
        lblBotaoProximo.setBounds(30, 630, 70, 70);

        lblArqueiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arqueiroCriarPersonagem.png"))); // NOI18N
        lblArqueiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblArqueiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblArqueiroMouseClicked(evt);
            }
        });
        jPanel1.add(lblArqueiro);
        lblArqueiro.setBounds(860, 150, 130, 160);

        lblArmadura.setFont(new java.awt.Font("ThaleahFat", 0, 38)); // NOI18N
        lblArmadura.setForeground(new java.awt.Color(1, 1, 1));
        lblArmadura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArmadura.setText("10 + 10 + 10 = 30");
        lblArmadura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblArmadura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblArmaduraMouseClicked(evt);
            }
        });
        jPanel1.add(lblArmadura);
        lblArmadura.setBounds(230, 360, 270, 39);

        lblPoder.setFont(new java.awt.Font("ThaleahFat", 0, 38)); // NOI18N
        lblPoder.setForeground(new java.awt.Color(1, 1, 1));
        lblPoder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPoder.setText("10 + 10 + 10 = 30");
        lblPoder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPoder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPoderMouseClicked(evt);
            }
        });
        jPanel1.add(lblPoder);
        lblPoder.setBounds(230, 420, 270, 39);

        lblForca.setFont(new java.awt.Font("ThaleahFat", 0, 38)); // NOI18N
        lblForca.setForeground(new java.awt.Color(1, 1, 1));
        lblForca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForca.setText("10 + 10 + 10 = 30");
        lblForca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblForca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForcaMouseClicked(evt);
            }
        });
        jPanel1.add(lblForca);
        lblForca.setBounds(230, 475, 270, 39);

        lblDados.setFont(new java.awt.Font("ThaleahFat", 0, 45)); // NOI18N
        lblDados.setForeground(new java.awt.Color(1, 1, 1));
        lblDados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDados.setText("5");
        lblDados.setToolTipText("");
        lblDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDadosMouseClicked(evt);
            }
        });
        jPanel1.add(lblDados);
        lblDados.setBounds(300, 240, 60, 46);

        lblVida.setFont(new java.awt.Font("ThaleahFat", 0, 38)); // NOI18N
        lblVida.setForeground(new java.awt.Color(1, 1, 1));
        lblVida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVida.setText("10 + 10 + 10 = 30");
        lblVida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVidaMouseClicked(evt);
            }
        });
        jPanel1.add(lblVida);
        lblVida.setBounds(230, 295, 270, 39);

        imageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/criarPersonagemFundo.png"))); // NOI18N
        jPanel1.add(imageBackground);
        imageBackground.setBounds(0, 0, 1030, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblArqueiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArqueiroMouseClicked
        // caso tenha escolhido a classe arqueiro, atualiza os os valores para se ajustar a classe
        lblGuerreiro.setEnabled(false);
        lblMago.setEnabled(false);
        lblArqueiro.setEnabled(true);
        classe = "arqueiro";
        if (vidaBonus != 0) 
            vidaTemp -= vidaBonus;
        vidaBonus = 4;

        if (armaduraBonus != 0) 
            armaduraTemp -= armaduraBonus;
        armaduraBonus = 6;

        if (poderBonus != 0) 
            poderTemp -= poderBonus;
        poderBonus = 4;

        if (forcaBonus != 0) 
            forcaTemp -= forcaBonus;
        forcaBonus = 4;
        
        atualizaValores();
    }//GEN-LAST:event_lblArqueiroMouseClicked

    private void lblMagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMagoMouseClicked
        // caso tenha escolhido a classe mago, atualiza os os valores para se ajustar a classe
        lblGuerreiro.setEnabled(false);
        lblArqueiro.setEnabled(false);
        lblMago.setEnabled(true);
        classe = "mago";
        
        if(vidaBonus != 0)
            vidaTemp -= vidaBonus;
        vidaBonus = 3;
 
        if (armaduraBonus != 0) 
            armaduraTemp -= armaduraBonus;
        armaduraBonus = 2;
        
        if (poderBonus != 0) 
            poderTemp -= poderBonus;
        poderBonus = 8;
        
        if (forcaBonus != 0) 
            forcaTemp -= forcaBonus;
        forcaBonus = 2;
        
       atualizaValores();
    }//GEN-LAST:event_lblMagoMouseClicked

    private void lblGuerreiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuerreiroMouseClicked
        // caso tenha escolhido a classe guerreiro, atualiza os os valores para se ajustar a classe
        lblArqueiro.setEnabled(false);
        lblMago.setEnabled(false);
        lblGuerreiro.setEnabled(true);
        classe = "guerreiro";
        if (vidaBonus != 0) 
            vidaTemp -= vidaBonus;
        vidaBonus = 5;

        if (armaduraBonus != 0) 
            armaduraTemp -= armaduraBonus;
        armaduraBonus = 4;

        if (poderBonus != 0) 
            poderTemp -= poderBonus;
        poderBonus = 1;
        
        if (forcaBonus != 0) 
            forcaTemp -= forcaBonus;
        forcaBonus = 6;
        
        atualizaValores();
    }//GEN-LAST:event_lblGuerreiroMouseClicked

    private void lblBotaoProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoProximoMouseClicked
        
        nome = txtNome.getText();
        
        if(nome.equals("")) // checa se tem nome
            JOptionPane.showMessageDialog(null, "Insira um nome para seu personagem!");
        else if(classe.equals("")) // checa se tem alguma classe selecionada
            JOptionPane.showMessageDialog(null, "Escolha uma classe");
        else{
            // cria o personagem
            perso.setNome(nome);
            perso.setClasse(classe);
            perso.setArmadura(armaduraTemp);
            perso.setForca(forcaTemp);
            perso.setPoder(poderTemp);
            perso.setVida(vidaTemp);
            perso.setVidaMax(vidaTemp+5);
            
            CriarJogador.perso.set(CriarJogador.personagemDaVez, perso);
            setVisible(false);
            new CriarJogador().setVisible(true);
        }
        
        
    }//GEN-LAST:event_lblBotaoProximoMouseClicked

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void lblVidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVidaMouseClicked
        geraValoresVida();
    }//GEN-LAST:event_lblVidaMouseClicked

    private void lblArmaduraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArmaduraMouseClicked
        geraValoresArmadura();
    }//GEN-LAST:event_lblArmaduraMouseClicked

    private void lblPoderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPoderMouseClicked
        geraValoresPoder();
    }//GEN-LAST:event_lblPoderMouseClicked

    private void lblForcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForcaMouseClicked
        geraValoresForca();
    }//GEN-LAST:event_lblForcaMouseClicked

    private void lblDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDadosMouseClicked

    private void lblBotaoProximoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoProximoMousePressed
        lblBotaoProximo.setBounds(30, 635, 70, 70);
    }//GEN-LAST:event_lblBotaoProximoMousePressed

    private void lblBotaoProximoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoProximoMouseReleased
        lblBotaoProximo.setBounds(30, 630, 70, 70);
    }//GEN-LAST:event_lblBotaoProximoMouseReleased

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarPersonagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageBackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArmadura;
    private javax.swing.JLabel lblArqueiro;
    private javax.swing.JLabel lblBotaoProximo;
    private javax.swing.JLabel lblDados;
    private javax.swing.JLabel lblForca;
    private javax.swing.JLabel lblGuerreiro;
    private javax.swing.JLabel lblMago;
    private javax.swing.JLabel lblPoder;
    private javax.swing.JLabel lblVida;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

    private void geraValoresVida() { // gera dois novos valores para o atributo vida
        
        if(qntDados > 0){
            
            vidaDados = "";

            int dado = gerador.nextInt(5) + 1;
            vidaTemp = dado;
            vidaDados += dado + " + ";

            dado = gerador.nextInt(5) + 1;
            vidaTemp += dado;
            vidaDados += dado + " + ";

            vidaTemp += vidaBonus;
            vidaDados += vidaBonus + " = " + vidaTemp;

            lblVida.setText(vidaDados);
            
            qntDados--;
            lblDados.setText(qntDados + "");

        } else {
            JOptionPane.showMessageDialog(null,"Você nao tem mais dados para rodar os atributos","Vai ter que ser isso mesmo",JOptionPane.ERROR_MESSAGE);
        }

    }
    
    private void geraValoresArmadura() {// gera dois novos valores para o atributo armadura
        
        if(qntDados > 0){   // se ainda tem dados
            armaduraDados = "";

            int dado = gerador.nextInt(5) + 1;  //gera um int entre 1 e 6
            armaduraTemp = dado;
            armaduraDados += dado + " + ";

            dado = gerador.nextInt(5) + 1;
            armaduraTemp += dado;
            armaduraDados += dado + " + ";

            armaduraTemp += armaduraBonus;
            armaduraDados += armaduraBonus + " = " + armaduraTemp;

            lblArmadura.setText(armaduraDados);
            
            qntDados--;
            lblDados.setText(qntDados + "");
             
        }else{
            JOptionPane.showMessageDialog(null, "Você nao tem mais dados para rodar os atributos");
        }

    }
    
    private void geraValoresPoder() { // gera dois novos valores para o atributo poder
        
        if(qntDados > 0){
            poderDados = "";

            int dado = gerador.nextInt(5) + 1;
            poderTemp = dado;
            poderDados += dado + " + ";

            dado = gerador.nextInt(5) + 1;
            poderTemp += dado;
            poderDados += dado + " + ";

            poderTemp += poderBonus;
            poderDados += poderBonus + " = " + poderTemp;

            lblPoder.setText(poderDados);
            qntDados--;
            lblDados.setText(qntDados + "");
             
        }else{
            JOptionPane.showMessageDialog(null, "Você nao tem mais dados para rodar os atributos");
        }

    }
    
    private void geraValoresForca() {// gera dois novos valores para o atributo vida
        
        if(qntDados >0){
            forcaDados = "";

            int dado = gerador.nextInt(5) + 1;
            forcaTemp = dado;
            forcaDados += dado + " + ";

            dado = gerador.nextInt(5) + 1;
            forcaTemp += dado;
            forcaDados += dado + " + ";

            forcaTemp += forcaBonus;
            forcaDados += forcaBonus + " = " + forcaTemp;

            lblForca.setText(forcaDados);
            qntDados--;
            lblDados.setText(qntDados + "");
            
        }else{
            JOptionPane.showMessageDialog(null, "Você nao tem mais dados para rodar os atributos");
        }

    }
    
    private void atualizaValores(){ // atualiza na interface grafica os valores dos atributos
        String valoresVida = vidaDados.substring(0, 7);
        vidaTemp += vidaBonus;
        valoresVida += vidaBonus + " = " + vidaTemp;
        lblVida.setText(valoresVida);

        String valoresArmadura = armaduraDados.substring(0, 7);
        armaduraTemp += armaduraBonus;
        valoresArmadura += armaduraBonus + " = " + armaduraTemp;
        lblArmadura.setText(valoresArmadura);
        
        String valoresPoder = poderDados.substring(0, 7);
        poderTemp += poderBonus;
        valoresPoder += poderBonus + " = " + poderTemp;
        lblPoder.setText(valoresPoder);
        
        String valoresForca = forcaDados.substring(0, 7);
        forcaTemp += forcaBonus;
        valoresForca += forcaBonus + " = " + forcaTemp;
        lblForca.setText(valoresForca);
    }
}
