package jogo;

import aLojinhaClasses.Jogador;
import javax.swing.JOptionPane;


public class Inicial extends javax.swing.JFrame {
    static Jogador jogador;
    private Jogador retorno;

    public Inicial() {
        initComponents();
        jogador = new Jogador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBotaoContinuar = new javax.swing.JLabel();
        lblBotaoCreditos = new javax.swing.JLabel();
        lblBotaoNovoJogo = new javax.swing.JLabel();
        imageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/icone.png")).getImage());
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(null);

        lblBotaoContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicialBotaoContinuar.png"))); // NOI18N
        lblBotaoContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBotaoContinuarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBotaoContinuarMouseReleased(evt);
            }
        });
        jPanel1.add(lblBotaoContinuar);
        lblBotaoContinuar.setBounds(330, 300, 380, 80);

        lblBotaoCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicialBotaoCreditos.png"))); // NOI18N
        lblBotaoCreditos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBotaoCreditosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBotaoCreditosMouseReleased(evt);
            }
        });
        jPanel1.add(lblBotaoCreditos);
        lblBotaoCreditos.setBounds(330, 390, 380, 80);

        lblBotaoNovoJogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicialBotaoNovoJogo.png"))); // NOI18N
        lblBotaoNovoJogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoNovoJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBotaoNovoJogoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBotaoNovoJogoMouseReleased(evt);
            }
        });
        jPanel1.add(lblBotaoNovoJogo);
        lblBotaoNovoJogo.setBounds(330, 210, 380, 80);
        lblBotaoNovoJogo.getAccessibleContext().setAccessibleDescription("");

        imageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicialFundo.png"))); // NOI18N
        jPanel1.add(imageBackground);
        imageBackground.setBounds(0, 0, 1030, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBotaoNovoJogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoNovoJogoMousePressed
        // TODO add your handling code here:
        lblBotaoNovoJogo.setBounds(330, 215, 380, 80);
    }//GEN-LAST:event_lblBotaoNovoJogoMousePressed

    private void lblBotaoNovoJogoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoNovoJogoMouseReleased

        lblBotaoNovoJogo.setBounds(330, 210, 380, 80);
        // pede o nome do jogador
        String nome = JOptionPane.showInputDialog(null, "Digite seu nome:", "Novo Jogador", JOptionPane.QUESTION_MESSAGE);
        
        if(nome != null){ // se o jogador nao clicou em cancelar
            while (nome.equals("") || nome.length() >= 15) { // enquanto o usuario nao digitar um nome valido
                if (nome.length() >= 15) {
                    JOptionPane.showMessageDialog(null, "O nome deve conter no maximo 15 letras!");
                } else if (nome.equals("")) {
                    JOptionPane.showMessageDialog(null, "Por favor insira um nome!");
                }
                nome = JOptionPane.showInputDialog("Digite seu nome:");
            }
            // atualiza os dados do jogador e vai para a criação dos personagens
            jogador.setNome(nome);
            setVisible(false);
            new CriarJogador().setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_lblBotaoNovoJogoMouseReleased

    private void lblBotaoContinuarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoContinuarMousePressed
        // TODO add your handling code here:
        lblBotaoContinuar.setBounds(330, 305, 380, 80);
    }//GEN-LAST:event_lblBotaoContinuarMousePressed

    private void lblBotaoContinuarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoContinuarMouseReleased
        // TODO add your handling code here:
        lblBotaoContinuar.setBounds(330, 300, 380, 80);
        
                
        retorno = manipulaArquivos.carregaJogo();
        
        if(retorno.getNome() == null){
            JOptionPane.showMessageDialog(null,"Não foi encontrado nenhum jogo.","Erro ao localizar jogo",JOptionPane.ERROR_MESSAGE);
        }else{
            jogador = retorno;
            setVisible(false);
            new Combate().setVisible(true);
        }

    }//GEN-LAST:event_lblBotaoContinuarMouseReleased

    private void lblBotaoCreditosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoCreditosMousePressed
        // TODO add your handling code here:
        lblBotaoCreditos.setBounds(330, 395, 380, 80);
    }//GEN-LAST:event_lblBotaoCreditosMousePressed

    private void lblBotaoCreditosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoCreditosMouseReleased

        lblBotaoCreditos.setBounds(330, 390, 380, 80);
        setVisible(false);
        new Creditos().setVisible(true);
    }//GEN-LAST:event_lblBotaoCreditosMouseReleased

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageBackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBotaoContinuar;
    private javax.swing.JLabel lblBotaoCreditos;
    private javax.swing.JLabel lblBotaoNovoJogo;
    // End of variables declaration//GEN-END:variables
}
