package jogo;

import java.util.ArrayList;
import aLojinhaClasses.Item;
import aLojinhaClasses.Jogador;
import javax.swing.JOptionPane;
import aLojinhaClasses.Loja;
import aLojinhaClasses.Personagem;


public class Lojinha extends javax.swing.JFrame {
    static Jogador jogador;
    int carrinho = 0;
    Loja loja;
    Item estoque[];
    ArrayList<Item> itensComprados = new ArrayList<Item>();

    public Lojinha() {
        // cria uma nova lojinha
        loja = new Loja(Inicial.jogador.getLevelAtual()-1);
        estoque = loja.getEstoque();

        initComponents();
        
        atualizaDadosLoja();
        atualizaEstoque();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBotaoComprar = new javax.swing.JLabel();
        lblDinheiro = new javax.swing.JLabel();
        lblItem1 = new javax.swing.JLabel();
        lblCusto1 = new javax.swing.JLabel();
        lblItem2Img = new javax.swing.JLabel();
        lblItem2 = new javax.swing.JLabel();
        lblCusto2 = new javax.swing.JLabel();
        lblItem3Img = new javax.swing.JLabel();
        lblItem3 = new javax.swing.JLabel();
        lblCusto3 = new javax.swing.JLabel();
        lblCusto4 = new javax.swing.JLabel();
        lblItem4Img = new javax.swing.JLabel();
        lblItem4 = new javax.swing.JLabel();
        lblCusto5 = new javax.swing.JLabel();
        lblItem5Img = new javax.swing.JLabel();
        lblItem5 = new javax.swing.JLabel();
        lblCarrinho = new javax.swing.JLabel();
        lblItem6Img = new javax.swing.JLabel();
        lblItem6 = new javax.swing.JLabel();
        lblCusto6 = new javax.swing.JLabel();
        lblItem1Img = new javax.swing.JLabel();
        lblLojaFrase = new javax.swing.JLabel();
        lblLojaNome = new javax.swing.JLabel();
        imageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/icone.png")).getImage());
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(null);

        lblBotaoComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/finalizarCompra.png"))); // NOI18N
        lblBotaoComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBotaoComprarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBotaoComprarMouseReleased(evt);
            }
        });
        jPanel1.add(lblBotaoComprar);
        lblBotaoComprar.setBounds(560, 160, 450, 60);

        lblDinheiro.setFont(new java.awt.Font("ThaleahFat", 0, 60)); // NOI18N
        lblDinheiro.setForeground(new java.awt.Color(1, 1, 1));
        lblDinheiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDinheiro.setText("$999");
        jPanel1.add(lblDinheiro);
        lblDinheiro.setBounds(860, 110, 140, 40);

        lblItem1.setFont(new java.awt.Font("ThaleahFat", 0, 60)); // NOI18N
        lblItem1.setForeground(new java.awt.Color(1, 1, 1));
        lblItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem1.setText("Varinha +10\n");
        lblItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItem1MouseClicked(evt);
            }
        });
        jPanel1.add(lblItem1);
        lblItem1.setBounds(110, 160, 300, 40);

        lblCusto1.setFont(new java.awt.Font("ThaleahFat", 0, 60)); // NOI18N
        lblCusto1.setForeground(new java.awt.Color(1, 1, 1));
        lblCusto1.setText("99");
        jPanel1.add(lblCusto1);
        lblCusto1.setBounds(450, 180, 60, 40);

        lblItem2Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/varinha.png"))); // NOI18N
        lblItem2Img.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblItem2Img);
        lblItem2Img.setBounds(30, 230, 70, 80);

        lblItem2.setFont(new java.awt.Font("ThaleahFat", 0, 60)); // NOI18N
        lblItem2.setForeground(new java.awt.Color(1, 1, 1));
        lblItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem2.setText("Varinha +10\n");
        lblItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItem2MouseClicked(evt);
            }
        });
        jPanel1.add(lblItem2);
        lblItem2.setBounds(100, 250, 300, 40);

        lblCusto2.setFont(new java.awt.Font("ThaleahFat", 0, 60)); // NOI18N
        lblCusto2.setForeground(new java.awt.Color(1, 1, 1));
        lblCusto2.setText("99");
        jPanel1.add(lblCusto2);
        lblCusto2.setBounds(450, 280, 60, 40);

        lblItem3Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/varinha.png"))); // NOI18N
        lblItem3Img.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblItem3Img);
        lblItem3Img.setBounds(30, 320, 70, 80);

        lblItem3.setFont(new java.awt.Font("ThaleahFat", 0, 60)); // NOI18N
        lblItem3.setForeground(new java.awt.Color(1, 1, 1));
        lblItem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem3.setText("Varinha +10\n");
        lblItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItem3MouseClicked(evt);
            }
        });
        jPanel1.add(lblItem3);
        lblItem3.setBounds(100, 340, 300, 40);

        lblCusto3.setFont(new java.awt.Font("ThaleahFat", 0, 60)); // NOI18N
        lblCusto3.setForeground(new java.awt.Color(1, 1, 1));
        lblCusto3.setText("99");
        jPanel1.add(lblCusto3);
        lblCusto3.setBounds(450, 370, 60, 40);

        lblCusto4.setFont(new java.awt.Font("ThaleahFat", 0, 60)); // NOI18N
        lblCusto4.setForeground(new java.awt.Color(1, 1, 1));
        lblCusto4.setText("99");
        jPanel1.add(lblCusto4);
        lblCusto4.setBounds(450, 470, 60, 40);

        lblItem4Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/varinha.png"))); // NOI18N
        lblItem4Img.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblItem4Img);
        lblItem4Img.setBounds(30, 420, 70, 80);

        lblItem4.setFont(new java.awt.Font("ThaleahFat", 0, 60)); // NOI18N
        lblItem4.setForeground(new java.awt.Color(1, 1, 1));
        lblItem4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem4.setText("Varinha +10\n");
        lblItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItem4MouseClicked(evt);
            }
        });
        jPanel1.add(lblItem4);
        lblItem4.setBounds(100, 440, 300, 40);

        lblCusto5.setFont(new java.awt.Font("ThaleahFat", 0, 60)); // NOI18N
        lblCusto5.setForeground(new java.awt.Color(1, 1, 1));
        lblCusto5.setText("99");
        jPanel1.add(lblCusto5);
        lblCusto5.setBounds(450, 570, 60, 40);

        lblItem5Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/varinha.png"))); // NOI18N
        lblItem5Img.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblItem5Img);
        lblItem5Img.setBounds(30, 520, 70, 80);

        lblItem5.setFont(new java.awt.Font("ThaleahFat", 0, 60)); // NOI18N
        lblItem5.setForeground(new java.awt.Color(1, 1, 1));
        lblItem5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem5.setText("Varinha +10\n");
        lblItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItem5MouseClicked(evt);
            }
        });
        jPanel1.add(lblItem5);
        lblItem5.setBounds(100, 540, 300, 40);

        lblCarrinho.setFont(new java.awt.Font("ThaleahFat", 0, 60)); // NOI18N
        lblCarrinho.setForeground(new java.awt.Color(2, 167, 36));
        lblCarrinho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarrinho.setText("$999");
        jPanel1.add(lblCarrinho);
        lblCarrinho.setBounds(590, 110, 140, 40);

        lblItem6Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/varinha.png"))); // NOI18N
        lblItem6Img.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblItem6Img);
        lblItem6Img.setBounds(30, 610, 70, 80);

        lblItem6.setFont(new java.awt.Font("ThaleahFat", 0, 60)); // NOI18N
        lblItem6.setForeground(new java.awt.Color(1, 1, 1));
        lblItem6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem6.setText("Varinha +10\n");
        lblItem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItem6MouseClicked(evt);
            }
        });
        jPanel1.add(lblItem6);
        lblItem6.setBounds(100, 630, 300, 40);

        lblCusto6.setFont(new java.awt.Font("ThaleahFat", 0, 60)); // NOI18N
        lblCusto6.setForeground(new java.awt.Color(1, 1, 1));
        lblCusto6.setText("99");
        jPanel1.add(lblCusto6);
        lblCusto6.setBounds(450, 660, 60, 40);

        lblItem1Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/varinha.png"))); // NOI18N
        lblItem1Img.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblItem1Img);
        lblItem1Img.setBounds(40, 140, 70, 80);

        lblLojaFrase.setFont(new java.awt.Font("ThaleahFat", 0, 30)); // NOI18N
        lblLojaFrase.setForeground(new java.awt.Color(1, 1, 1));
        lblLojaFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLojaFrase.setText("Mate o MONSTROS QUE ME DAO MEDO");
        jPanel1.add(lblLojaFrase);
        lblLojaFrase.setBounds(560, 620, 450, 90);

        lblLojaNome.setFont(new java.awt.Font("ThaleahFat", 0, 70)); // NOI18N
        lblLojaNome.setForeground(new java.awt.Color(1, 1, 1));
        lblLojaNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLojaNome.setText("Alfredo");
        jPanel1.add(lblLojaNome);
        lblLojaNome.setBounds(590, 300, 390, 60);

        imageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lojinhaFundo.png"))); // NOI18N
        jPanel1.add(imageBackground);
        imageBackground.setBounds(0, 0, 1030, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBotaoComprarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoComprarMouseReleased

        lblBotaoComprar.setBounds(560, 160, 450, 60);

        if(carrinho == 0){ // se nao comprou nada
            setVisible(false);
            if (Inicial.jogador.getLevelAtual() <= 10) {
                setVisible(false);
                new Combate().setVisible(true);
            }
        }else{
            if (carrinho > Inicial.jogador.getDinheiro()) { //  checa se o jogador pode comprar
                JOptionPane.showMessageDialog(null, "Vocâ nâo tem dinheiro suficiente", "", JOptionPane.ERROR_MESSAGE);
            } else {
                Inicial.jogador.pagarCompra(carrinho);
                ArrayList<Personagem> perso = Inicial.jogador.getPersonagens();

                itensComprados.forEach(item -> { // distrivui os itens para os personagens
                    if (item.getTipo().equals(perso.get(0).getTipoItem())) {
                        perso.get(0).recebeItem(item.getAtributo());
                    } else if (item.getTipo().equals(perso.get(1).getTipoItem())) {
                        perso.get(1).recebeItem(item.getAtributo());
                    }
                });

                setVisible(false);
                
                // salva e volta para o combate
                manipulaArquivos.salvaJogo(Inicial.jogador);
                new Combate().setVisible(true);
            }
        }
    }//GEN-LAST:event_lblBotaoComprarMouseReleased

    private void lblBotaoComprarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoComprarMousePressed

        lblBotaoComprar.setBounds(560, 165, 450, 60);
    }//GEN-LAST:event_lblBotaoComprarMousePressed

    private void lblItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItem1MouseClicked
        
        if(estoque[0].isNoCarrinho()){ // se o item ja ta no carrinho, tira
            lblItem1Img.setEnabled(false);
            lblItem1.setEnabled(false);

            carrinho -= estoque[0].getValor();
            estoque[0].setNoCarrinho(false);
            
            itensComprados.remove(estoque[0]);
        }else{ // se nao adiciona
            lblItem1Img.setEnabled(true);
            lblItem1.setEnabled(true);
            carrinho += estoque[0].getValor();
            estoque[0].setNoCarrinho(true);
            
            itensComprados.add(estoque[0]);
        }
        
        atualizaDadosLoja();
    }//GEN-LAST:event_lblItem1MouseClicked

    private void lblItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItem2MouseClicked

        if (estoque[1].isNoCarrinho()) {// se o item ja ta no carrinho, tira
            lblItem2Img.setEnabled(false);
            lblItem2.setEnabled(false);

            carrinho -= estoque[1].getValor();
            estoque[1].setNoCarrinho(false);

            itensComprados.remove(estoque[1]);
        } else { // se nao adiciona
            lblItem2Img.setEnabled(true);
            lblItem2.setEnabled(true);
            carrinho += estoque[1].getValor();
            estoque[1].setNoCarrinho(true);

            itensComprados.add(estoque[1]);
        }

        atualizaDadosLoja();
    }//GEN-LAST:event_lblItem2MouseClicked

    private void lblItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItem3MouseClicked

        if (estoque[2].isNoCarrinho()) {// se o item ja ta no carrinho, tira
            lblItem3Img.setEnabled(false);
            lblItem3.setEnabled(false);

            carrinho -= estoque[2].getValor();
            estoque[2].setNoCarrinho(false);

            itensComprados.remove(estoque[2]);
        } else {// se nao adiciona
            lblItem3Img.setEnabled(true);
            lblItem3.setEnabled(true);
            carrinho += estoque[2].getValor();
            estoque[2].setNoCarrinho(true);

            itensComprados.add(estoque[2]);
        }

        atualizaDadosLoja();
    }//GEN-LAST:event_lblItem3MouseClicked

    private void lblItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItem4MouseClicked
        
        if (estoque[3].isNoCarrinho()) {// se o item ja ta no carrinho, tira
            lblItem4Img.setEnabled(false);
            lblItem4.setEnabled(false);

            carrinho -= estoque[3].getValor();
            estoque[3].setNoCarrinho(false);

            itensComprados.remove(estoque[3]);
        } else {// se nao adiciona
            lblItem4Img.setEnabled(true);
            lblItem4.setEnabled(true);
            carrinho += estoque[3].getValor();
            estoque[3].setNoCarrinho(true);

            itensComprados.add(estoque[3]);
        }

        atualizaDadosLoja();
    }//GEN-LAST:event_lblItem4MouseClicked

    private void lblItem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItem5MouseClicked

        if (estoque[4].isNoCarrinho()) {// se o item ja ta no carrinho, tira
            lblItem5Img.setEnabled(false);
            lblItem5.setEnabled(false);

            carrinho -= estoque[4].getValor();
            estoque[4].setNoCarrinho(false);

            itensComprados.remove(estoque[4]);
        } else {// se nao adiciona
            lblItem5Img.setEnabled(true);
            lblItem5.setEnabled(true);
            carrinho += estoque[4].getValor();
            estoque[4].setNoCarrinho(true);

            itensComprados.add(estoque[4]);
        }

        atualizaDadosLoja();
    }//GEN-LAST:event_lblItem5MouseClicked

    private void lblItem6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItem6MouseClicked
                
        if(estoque[5].isNoCarrinho()){// se o item ja ta no carrinho, tira
            lblItem6Img.setEnabled(false);
            lblItem6.setEnabled(false);

            carrinho -= estoque[5].getValor();
            estoque[5].setNoCarrinho(false);
            
            itensComprados.remove(estoque[5]);
        }else{// se nao adiciona
            lblItem6Img.setEnabled(true);
            lblItem6.setEnabled(true);
            carrinho += estoque[5].getValor();
            estoque[5].setNoCarrinho(true);
            
            itensComprados.add(estoque[5]);
        }
        
        atualizaDadosLoja();
    }//GEN-LAST:event_lblItem6MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lojinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lojinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lojinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lojinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lojinha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageBackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBotaoComprar;
    private javax.swing.JLabel lblCarrinho;
    private javax.swing.JLabel lblCusto1;
    private javax.swing.JLabel lblCusto2;
    private javax.swing.JLabel lblCusto3;
    private javax.swing.JLabel lblCusto4;
    private javax.swing.JLabel lblCusto5;
    private javax.swing.JLabel lblCusto6;
    private javax.swing.JLabel lblDinheiro;
    private javax.swing.JLabel lblItem1;
    private javax.swing.JLabel lblItem1Img;
    private javax.swing.JLabel lblItem2;
    private javax.swing.JLabel lblItem2Img;
    private javax.swing.JLabel lblItem3;
    private javax.swing.JLabel lblItem3Img;
    private javax.swing.JLabel lblItem4;
    private javax.swing.JLabel lblItem4Img;
    private javax.swing.JLabel lblItem5;
    private javax.swing.JLabel lblItem5Img;
    private javax.swing.JLabel lblItem6;
    private javax.swing.JLabel lblItem6Img;
    private javax.swing.JLabel lblLojaFrase;
    private javax.swing.JLabel lblLojaNome;
    // End of variables declaration//GEN-END:variables


    private void atualizaDadosLoja() {// atualiza na interface grafica os dados da lojinha e da carteira do jogador
        
        lblLojaNome.setText(loja.getNome().split(",")[0]);
        lblLojaFrase.setText(loja.getNome().split(",")[1]);
        
        lblCarrinho.setText("$" + carrinho);
        if(carrinho >Inicial.jogador.getDinheiro()) // se o carrinho custa mais que o jogador pode comprar muda a cor da fonte
            lblCarrinho.setForeground(new java.awt.Color(217, 55, 36));
        else
            lblCarrinho.setForeground(new java.awt.Color(2, 167, 36));
        
        lblDinheiro.setText("$" + Inicial.jogador.getDinheiro());
    }
    
    private void atualizaEstoque() { // atualiza a interface grafica dos itens do estoque

        lblItem1.setText(estoque[0].getTipo() + " +" + estoque[0].getAtributo());
        lblCusto1.setText(estoque[0].getValor() + "");
        lblItem1Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + estoque[0].getTipo() + ".png")));
        
        lblItem2.setText(estoque[1].getTipo() + " +" + estoque[1].getAtributo());
        lblCusto2.setText(estoque[1].getValor() + "");
        lblItem2Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + estoque[1].getTipo() + ".png")));
        
        lblItem3.setText(estoque[2].getTipo() + " +" + estoque[2].getAtributo());
        lblCusto3.setText(estoque[2].getValor() + "");
        lblItem3Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + estoque[2].getTipo() + ".png")));
        
        lblItem4.setText(estoque[3].getTipo() + " +" + estoque[3].getAtributo());
        lblCusto4.setText(estoque[3].getValor() + "");
        lblItem4Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + estoque[3].getTipo() + ".png")));
        
        lblItem5.setText(estoque[4].getTipo() + " +" + estoque[4].getAtributo());
        lblCusto5.setText(estoque[4].getValor() + "");
        lblItem5Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + estoque[4].getTipo() + ".png")));
        
        lblItem6.setText(estoque[5].getTipo() + " +" + estoque[5].getAtributo());
        lblCusto6.setText(estoque[5].getValor() + "");
        lblItem6Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + estoque[5].getTipo() + ".png")));
        
        lblItem1.setEnabled(false);
        lblItem2.setEnabled(false);
        lblItem3.setEnabled(false);
        lblItem4.setEnabled(false);
        lblItem5.setEnabled(false);
        lblItem6.setEnabled(false);

        lblItem1Img.setEnabled(false);
        lblItem2Img.setEnabled(false);
        lblItem3Img.setEnabled(false);
        lblItem4Img.setEnabled(false);
        lblItem5Img.setEnabled(false);
        lblItem6Img.setEnabled(false);

    }
}

